# SwiftLint config for MDLWallet
# https://github.com/realm/SwiftLint

line_length:
  warning: 180
  error: 250

type_body_length:
  warning: 600
  error: 800

file_length:
  warning: 750
  error: 1000

function_body_length:
  warning: 70
  error: 90

cyclomatic_complexity:
  warning: 16
  error: 25

identifier_name:
  min_length: 2
  max_length: 50

excluded:
  - Tuist
  - .build
