# SwiftLint config for MDLWallet.
# Docs: https://realm.github.io/SwiftLint/rule-directory.html

# Paths to lint (relative to repo root when run from root)
included:
  - MDLWallet

# Exclude generated or third-party code
excluded:
  - MDLWallet/MDLWallet.xcworkspace
  - MDLWallet/.build
  - "**/Tuist/**"

# Rule configuration
opt_in_rules:
  - empty_count
  - explicit_init

disabled_rules:
  - trailing_whitespace   # often noisy in comments; enable if you want
  - line_length           # enable and set max to enforce (e.g. 120)

# Optional: enforce line length (uncomment to enable)
# line_length:
#   warning: 120
#   error: 150

# Reporter: xcode (default) or other; CI usually uses default
reporter: "xcode"
